spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
  h2:
    enabled: true
    path: /h2-console
    url: jdbc:h2:~/backend
    username: sa
    password: sa
    driver: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
